// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QTBWebBackend.Models;

public partial class Aereo
{
    public long Id { get; set; }

    public string Costruttore { get; set; }

    public string Modello { get; set; }

    public string Marche { get; set; }

    public int? PesoVuoto { get; set; }

    public int MinutiPregressi { get; set; }

    public long? OrametroId { get; set; }

    public virtual ICollection<AereoPosseduto> AereiPosseduti { get; set; } = new List<AereoPosseduto>();

    public virtual ICollection<Manutenzione> Manutenzioni { get; set; } = new List<Manutenzione>();

    public virtual TipoOrametro Orametro { get; set; }

    public virtual ICollection<ScadenzaAereo> ScadenzeAerei { get; set; } = new List<ScadenzaAereo>();

    public virtual ICollection<Volo> Voli { get; set; } = new List<Volo>();
}