// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QTBWebBackend.Models;

public partial class Aerei
{
    public long Id { get; set; }

    public string Costruttore { get; set; }

    public string Modello { get; set; }

    public string Marche { get; set; }

    public int? PesoVuoto { get; set; }

    public int MinutiPregressi { get; set; }

    public long? OrametroId { get; set; }

    public virtual ICollection<AereiPosseduti> AereiPosseduti { get; set; } = new List<AereiPosseduti>();

    public virtual ICollection<Manutenzioni> Manutenzioni { get; set; } = new List<Manutenzioni>();

    public virtual TipiOrametri Orametro { get; set; }

    public virtual ICollection<ScadenzeAerei> ScadenzeAerei { get; set; } = new List<ScadenzeAerei>();

    public virtual ICollection<Voli> Voli { get; set; } = new List<Voli>();
}