// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QTBWebBackend.Models;

public partial class Aeroporto
{
    public long Id { get; set; }

    public string Nome { get; set; }

    public string Denominazione { get; set; }

    public long TipoId { get; set; }

    public string Identificativo { get; set; }

    public string Coordinate { get; set; }

    public string Icao { get; set; }

    public string Iata { get; set; }

    public int? Qnh { get; set; }

    public string Qfu { get; set; }

    public int? Lunghezza { get; set; }

    public bool Asfalto { get; set; }

    public string Radio { get; set; }

    public string Indirizzo { get; set; }

    public string Cap { get; set; }

    public string Citta { get; set; }

    public string Provincia { get; set; }

    public string Nazione { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public string Web { get; set; }

    public string Note { get; set; }

    public virtual ICollection<Persona> Persone { get; set; } = new List<Persona>();

    public virtual TipoAeroporto Tipo { get; set; }

    public virtual ICollection<Volo> VoliAeroportoFine { get; set; } = new List<Volo>();

    public virtual ICollection<Volo> VoliAeroportoInizio { get; set; } = new List<Volo>();
}