// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QTBWebBackend.Models;

public partial class Login
{
    public long Id { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public long PersonaId { get; set; }

    public bool Attivo { get; set; }

    public DateTime? UltimoLogin { get; set; }

    public DateTime DataCreazione { get; set; }

    public virtual Persone Persona { get; set; }

    public virtual ICollection<Ruoli> Ruolo { get; set; } = new List<Ruoli>();
}