// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QTBWebBackend.Models;

public partial class Manutenzioni
{
    public long Id { get; set; }

    public bool Ordinaria { get; set; }

    public long TipoId { get; set; }

    public string Descrizione { get; set; }

    public DateTime Data { get; set; }

    public long AereoId { get; set; }

    public long? PersonaId { get; set; }

    public long? VoloId { get; set; }

    public virtual Aerei Aereo { get; set; }

    public virtual Persone Persona { get; set; }

    public virtual TipiManutenzioni Tipo { get; set; }

    public virtual Voli Volo { get; set; }
}