// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QTBWebBackend.Models;

public partial class Manutenzione
{
    public long Id { get; set; }

    public long TipoId { get; set; }

    public string Descrizione { get; set; }

    public DateTime Data { get; set; }

    public long AereoId { get; set; }

    public long? PersonaId { get; set; }

    public long? VoloId { get; set; }

    public virtual Aereo Aereo { get; set; }

    public virtual Persona Persona { get; set; }

    public virtual TipoManutenzione Tipo { get; set; }

    public virtual Volo Volo { get; set; }
}