// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QTBWebBackend.Models;

public partial class Persone
{
    public long Id { get; set; }

    public string Nome { get; set; }

    public string Cognome { get; set; }

    public string Indirizzo { get; set; }

    public string Email { get; set; }

    public DateOnly? DataNascita { get; set; }

    public string LuogoNascita { get; set; }

    public string CodiceFiscale { get; set; }

    public string Citta { get; set; }

    public string Cap { get; set; }

    public string Telefono { get; set; }

    public bool Pilota { get; set; }

    public int? MinutiPregressi { get; set; }

    public long? AeroportoBaseId { get; set; }

    public string Tessera { get; set; }

    public virtual ICollection<AereiPosseduti> AereiPosseduti { get; set; } = new List<AereiPosseduti>();

    public virtual Aeroporti AeroportoBase { get; set; }

    public virtual Login Login { get; set; }

    public virtual ICollection<Manutenzioni> Manutenzioni { get; set; } = new List<Manutenzioni>();

    public virtual ICollection<ScadenzePersone> ScadenzePersone { get; set; } = new List<ScadenzePersone>();

    public virtual ICollection<Voli> VoliOwner { get; set; } = new List<Voli>();

    public virtual ICollection<Voli> VoliPasseggero { get; set; } = new List<Voli>();

    public virtual ICollection<Voli> VoliPilota { get; set; } = new List<Voli>();
}