// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QTBWebBackend.Models;

public partial class Persona
{
    public long Id { get; set; }

    public string Nome { get; set; }

    public string Cognome { get; set; }

    public string Indirizzo { get; set; }

    public string Email { get; set; }

    public DateOnly? DataNascita { get; set; }

    public string LuogoNascita { get; set; }

    public string CodiceFiscale { get; set; }

    public string Citta { get; set; }

    public string Cap { get; set; }

    public string Telefono { get; set; }

    public bool Pilota { get; set; }

    public int? MinutiPregressi { get; set; }

    public long? AeroportoBaseId { get; set; }

    public string Tessera { get; set; }

    public virtual ICollection<AereoPosseduto> AereiPosseduti { get; set; } = new List<AereoPosseduto>();

    public virtual Aeroporto AeroportoBase { get; set; }

    public virtual Login Login { get; set; }

    public virtual ICollection<Manutenzione> Manutenzioni { get; set; } = new List<Manutenzione>();

    public virtual ICollection<ScadenzaPersona> ScadenzePersone { get; set; } = new List<ScadenzaPersona>();

    public virtual ICollection<Volo> VoliOwner { get; set; } = new List<Volo>();

    public virtual ICollection<Volo> VoliPasseggero { get; set; } = new List<Volo>();

    public virtual ICollection<Volo> VoliPilota { get; set; } = new List<Volo>();
}