// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QTBWebBackend.Models;

public partial class TipoVolo
{
    public long Id { get; set; }

    public string Descrizione { get; set; }

    public virtual ICollection<Volo> Voli { get; set; } = new List<Volo>();
}