// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QTBWebBackend.Models;

public partial class Voli
{
    public long Id { get; set; }

    public string Descrizione { get; set; }

    public long TipoId { get; set; }

    public long PilotaId { get; set; }

    public long? PasseggeroId { get; set; }

    public long? OwnerId { get; set; }

    public long AereoId { get; set; }

    public DateTime? OraInizio { get; set; }

    public string OraLocaleDecollo { get; set; }

    public int OrametroOreInizio { get; set; }

    public int OrametroMinutiInizio { get; set; }

    public DateTime OraFine { get; set; }

    public string OraLocaleAtterraggio { get; set; }

    public int OrametroOreFine { get; set; }

    public int OrametroMinutiFine { get; set; }

    public int? Durata { get; set; }

    public int? CarburanteInizialeSx { get; set; }

    public int? CarburanteInizialeDx { get; set; }

    public int? CarburanteAggiuntoSx { get; set; }

    public int? CarburanteAggiuntoDx { get; set; }

    public int? Olio { get; set; }

    public int? PesoOccupanti { get; set; }

    public int? Bagaglio { get; set; }

    public long AeroportoInizioId { get; set; }

    public long AeroportoFineId { get; set; }

    public virtual Aerei Aereo { get; set; }

    public virtual Aeroporti AeroportoFine { get; set; }

    public virtual Aeroporti AeroportoInizio { get; set; }

    public virtual ICollection<Manutenzioni> Manutenzioni { get; set; } = new List<Manutenzioni>();

    public virtual Persone Owner { get; set; }

    public virtual Persone Passeggero { get; set; }

    public virtual Persone Pilota { get; set; }

    public virtual TipiVoli Tipo { get; set; }
}