// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QTBWebBackend.Models;

public partial class Volo
{
    public long Id { get; set; }

    public string Descrizione { get; set; }

    public long TipoId { get; set; }

    public long PilotaId { get; set; }

    public long? PasseggeroId { get; set; }

    public long? OwnerId { get; set; }

    public long AereoId { get; set; }

    public DateTime OraDecollo { get; set; }

    public int OrametroOreInizio { get; set; }

    public int OrametroMinutiInizio { get; set; }

    public DateTime? OraAtterraggio { get; set; }

    public int? OrametroOreFine { get; set; }

    public int? OrametroMinutiFine { get; set; }

    public int? CarburanteInizialeSx { get; set; }

    public int? CarburanteInizialeDx { get; set; }

    public int? CarburanteAggiuntoSx { get; set; }

    public int? CarburanteAggiuntoDx { get; set; }

    public int? Olio { get; set; }

    public int? PesoOccupanti { get; set; }

    public int? Bagaglio { get; set; }

    public long AeroportoInizioId { get; set; }

    public long? AeroportoFineId { get; set; }

    public virtual Aereo Aereo { get; set; }

    public virtual Aeroporto AeroportoFine { get; set; }

    public virtual Aeroporto AeroportoInizio { get; set; }

    public virtual ICollection<Manutenzione> Manutenzioni { get; set; } = new List<Manutenzione>();

    public virtual Persona Owner { get; set; }

    public virtual Persona Passeggero { get; set; }

    public virtual Persona Pilota { get; set; }

    public virtual TipoVolo Tipo { get; set; }
}